name: CI

on:
  push:

jobs:
  test-on-push:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "check is GH_PAT exists"
        env: 
            pat: ${{ secrets.GH_PAT }}
        if: ${{ env.pat == '' }}
        run: 'echo "echo the secret \"GH_PAT\" has not been made; echo please go to \"settings \> secrets \> actions\" to create it"'
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}
          repository: StandOfGiants/NavyLovin
      - uses: actions/checkout@v2
        with:
          path: dialog
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-build-stable-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
        if: runner.os == 'linux'
      - name: Build & run tests
        run: cargo test
