name: Check Pull Request

on:
  pull_request_target:
    types: [labeled]

jobs:
  test-on-pr:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - uses: suzuki-shunsuke/get-pr-action@v0.1.0
        id: pr
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}
          repository: StandOfGiants/NavyLovin
      - uses: actions/checkout@v2
        with:
          path: dialog
          ref: ${{steps.get-pr.outputs.merge_commit_sha}}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-build-stable-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
        if: runner.os == 'linux'
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
